services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db_local
    ports:
      - 27017:27017
    volumes:
      - mongodb_local:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - MongoNetwork
    restart: always

networks:
  MongoNetwork:

volumes:
  mongodb_local:
