name: mini-rag
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.11.9
  - pip=24.2
  - pip:
      - python-dotenv==1.0.1
      - wandb==0.18.5
      - emoji==2.14.0
      - rich[jupyter]==13.9.2
      - tqdm==4.66.5
      - fastapi[standard]==0.115.4
      - uvicorn[standard]==0.32.0
      - python-multipart==0.0.17
      - pydantic==2.9.2
      - pydantic-settings==2.6.1
      - aiofiles==24.1.0
      - langchain==0.3.7
      - langchain-community==0.3.5
      - langchain-text-splitters==0.3.2
      - PyMuPDF==1.24.13
